
import type { Investigation } from "../../services/investigationService";
import { FaBrain, FaRobot, FaCheckCircle, FaExclamationTriangle } from "react-icons/fa";

interface Props {
  investigation: Investigation;
}

export default function AiAnalysisPanel({ investigation }: Props) {
  const { attack } = investigation;
  
  // Calculate deterministic factors to feed the "AI" representation
  const isHighRisk = attack.severity === "Critical" || attack.severity === "High";
  const confidenceScore = attack.confidence || 0;
  
  // Mock AI generated text based strictly on factual inputs (no fabrication)
  const aiInterpretation = `Based on the threat intelligence ingestion from ${attack.source}, the indicator ${attack.indicator} is associated with ${attack.attack_type || "suspicious activity"}. The confidence score provided by the collector is ${confidenceScore}%. ${isHighRisk ? "This represents a high-risk operational threat." : "This is a low-to-medium priority intelligence indicator."} ${attack.target_state && attack.target_state.includes("Confirmed") ? "The telemetry explicitly indicates a confirmed targeting of Indian infrastructure." : "There is no direct evidence of this indicator actively targeting India at this time."}`;

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 32 }}>
      <h2 className="section-title" style={{ fontSize: 20, margin: 0, color: "#fff", display: "flex", alignItems: "center", gap: 8 }}>
        <FaBrain /> AI Threat Analysis
      </h2>
      
      <div style={{ background: "rgba(90, 194, 240, 0.1)", border: "1px solid rgba(90, 194, 240, 0.3)", padding: 16, borderRadius: 8, display: "flex", gap: 12, color: "#5ac2f0", fontSize: 13 }}>
        <FaRobot size={18} />
        <div>
          <strong>AI Interpretation Notice:</strong> The following analysis is generated by AI based strictly on factual telemetry. It is designed to assist analysts but should be verified.
        </div>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 300px", gap: 24 }}>
        <div style={{ background: "#09121f", padding: 32, borderRadius: 12, border: "1px solid #1a2d45" }}>
          <h3 style={{ margin: 0, color: "#fff", fontSize: 18, marginBottom: 16 }}>Behavioral Interpretation</h3>
          <p style={{ color: "#7889a3", lineHeight: 1.6, fontSize: 15 }}>
            {aiInterpretation}
          </p>
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <div style={{ background: "#09121f", padding: 24, borderRadius: 12, border: "1px solid #1a2d45", textAlign: "center" }}>
            <div className="muted" style={{ marginBottom: 12 }}>Calculated Risk Score</div>
            <div style={{ fontSize: 48, fontWeight: 800, color: isHighRisk ? "#ff6374" : "#3be2a5" }}>
              {Math.min(100, Math.max(0, confidenceScore + (isHighRisk ? 20 : 0)))}
            </div>
          </div>
          
          <div style={{ background: "#09121f", padding: 24, borderRadius: 12, border: "1px solid #1a2d45" }}>
            <div className="muted" style={{ marginBottom: 12 }}>Key Indicators</div>
            <ul style={{ margin: 0, padding: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: 12 }}>
              <li style={{ display: "flex", gap: 8, color: "#fff", fontSize: 13 }}>
                <FaCheckCircle color="#3be2a5" /> Validated by {attack.source}
              </li>
              {isHighRisk && (
                <li style={{ display: "flex", gap: 8, color: "#fff", fontSize: 13 }}>
                  <FaExclamationTriangle color="#ff6374" /> High severity classification
                </li>
              )}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
