import random
import asyncio
from datetime import datetime
from sqlalchemy.orm import Session

from app.database.database import SessionLocal
from app.models.attack import Attack
from app.services.websocket_manager import manager
from app.crud.settings import get_collector_settings

# ============================================================
# RFC 5737 documentation-safe IP ranges (192.0.2.0/24,
# 198.51.100.0/24, 203.0.113.0/24). These MUST be used
# instead of real public IPs for simulated events.
# ============================================================
ATTACK_VECTORS = [
    ("Credential Stuffing", "Critical", "T1110", [22, 3389, 80, 443]),
    ("Malware Beaconing", "High", "T1071", [443, 8080, 445]),
    ("Exploit Attempt", "High", "T1190", [80, 443, 8080]),
    ("Reconnaissance Scan", "Medium", "T1595", [80, 22, 21, 445, 1433]),
    ("Port Sweep", "Low", "T1046", [22, 23, 80, 443, 3389, 8080]),
    ("DDoS Flood", "Critical", "T1498", [80, 443, 53, 123]),
    ("SQL Injection", "High", "T1190", [80, 443, 8080]),
    ("Ransomware Payload", "Critical", "T1486", [445, 139, 3389]),
    ("Phishing Redirection", "Medium", "T1566", [80, 443])
]

# Documentation-safe IPs per simulated country
COUNTRIES = [
    ("Russia", "RU", ["192.0.2.10", "192.0.2.11", "192.0.2.12", "192.0.2.13"]),
    ("China", "CN", ["192.0.2.20", "192.0.2.21", "192.0.2.22", "192.0.2.23"]),
    ("United States", "US", ["198.51.100.10", "198.51.100.11", "198.51.100.12", "198.51.100.13"]),
    ("Germany", "DE", ["198.51.100.20", "198.51.100.21", "198.51.100.22", "198.51.100.23"]),
    ("Netherlands", "NL", ["198.51.100.30", "198.51.100.31", "198.51.100.32", "198.51.100.33"]),
    ("Turkey", "TR", ["203.0.113.10", "203.0.113.11", "203.0.113.12", "203.0.113.13"]),
    ("Brazil", "BR", ["203.0.113.20", "203.0.113.21", "203.0.113.22", "203.0.113.23"]),
    ("United Kingdom", "GB", ["203.0.113.30", "203.0.113.31", "203.0.113.32", "203.0.113.33"]),
    ("Ukraine", "UA", ["203.0.113.40", "203.0.113.41", "203.0.113.42", "203.0.113.43"]),
    ("Singapore", "SG", ["203.0.113.50", "203.0.113.51", "203.0.113.52", "203.0.113.53"])
]

STATES = ["Maharashtra", "Karnataka", "Delhi", "Tamil Nadu", "Telangana", "Gujarat", "Kerala", "West Bengal", "Uttar Pradesh", "Andhra Pradesh"]


async def run_telemetry_simulator():
    """Continuously generate simulated attack events when simulation_mode is enabled.

    IMPORTANT:
    - source_type is always SIMULATOR
    - event_classification is always SIMULATED
    - is_confirmed_india_target is always False
    - IPs are from RFC 5737 documentation ranges only
    """
    print("Telemetry Simulator: Waiting 5 seconds before starting...")
    await asyncio.sleep(5)
    print("Telemetry Simulator Loop active.")

    while True:
        db = SessionLocal()
        try:
            settings = get_collector_settings(db)
            if not settings.simulation_mode:
                db.close()
                await asyncio.sleep(5)
                continue

            # Generate random simulated attack
            country, country_code, ips = random.choice(COUNTRIES)
            ip = random.choice(ips)
            state = random.choice(STATES)
            attack_type, severity, mitre, ports = random.choice(ATTACK_VECTORS)
            port = random.choice(ports)
            confidence = random.randint(70, 99)

            db_attack = Attack(
                indicator=ip,
                indicator_type="ip",
                source="simulator",
                source_type="SIMULATOR",
                event_classification="SIMULATED",
                source_country=country,
                source_country_code=country_code,
                target_country="India",
                target_state=state,
                destination_port=port,
                destination_protocol="tcp",
                attack_type=attack_type,
                severity=severity,
                confidence=confidence,
                mitre_tactic=mitre,
                description=f"Simulated event: {attack_type} targeting {state}, India. Destination port: {port}.",
                classification_reason="Synthetic demonstration event generated by ICTIP telemetry simulator.",
                is_confirmed_india_target=False,
                timestamp=datetime.utcnow()
            )

            db.add(db_attack)
            db.commit()
            db.refresh(db_attack)

            # Broadcast via WebSocket with explicit classification
            event = {
                "id": f"sim-{db_attack.id}",
                "eventUuid": db_attack.event_uuid,
                "indicator": db_attack.indicator,
                "indicatorType": db_attack.indicator_type,
                "source": "simulator",
                "sourceType": "SIMULATOR",
                "eventClassification": "SIMULATED",
                "sourceIp": db_attack.indicator,
                "sourceCountry": db_attack.source_country,
                "countryCode": db_attack.source_country_code,
                "targetCountry": db_attack.target_country,
                "targetState": db_attack.target_state,
                "targetCity": None,
                "destinationPort": db_attack.destination_port,
                "protocol": db_attack.destination_protocol,
                "attackType": db_attack.attack_type,
                "severity": db_attack.severity,
                "confidence": db_attack.confidence,
                "mitre": db_attack.mitre_tactic,
                "description": db_attack.description,
                "timestamp": db_attack.timestamp.isoformat() + "Z",
                "isConfirmedIndiaTarget": False,
                "sensor": None
            }

            await manager.broadcast(event)

        except Exception as e:
            print(f"Error in telemetry simulator loop: {e}")
        finally:
            db.close()

        # Random sleep between 2 and 6 seconds to feel natural
        await asyncio.sleep(random.uniform(2.0, 6.0))
